version: 2.1
parameters:
      ENV:
        type: string
        default: "stage_up"
      Browser:
        type: string
        default: "ff"
      Tag:
        type: string
        default: "@UP_pin"
jobs:
  build:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    working_directory: ~/demo2
    #parallelism: 
    resource_class: large

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m   
      ENV_UP: '<< pipeline.parameters.ENV >>'
      Browser_UP: '<< pipeline.parameters.Browser >>'
      Tag_UP: '<< pipeline.parameters.Tag >>'
      #ENV: 'stage_up' 
      #Browser: 'ff'
      #Tag: '@UP_signIn'
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: mvn dependency:go-offline  
      #- run: circleci tests glob "**/*.rb" | circleci tests split --split-by=timings --time-default=10s 
      #- run: sudo apt update && sudo apt install wget 
      #- run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      #- run: sudo apt install ./google-chrome-stable_current_amd64.deb 
      #- run: apt install chromium-chromedriver
      #- run: google-chrome --version
      - run:
          name: Running X virtual framebuffer
          command: Xvfb :0 -ac &
      - run:
          name: Run Tests
          command: |
            export DISPLAY=:99
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      # run tests!
      #- run: sudo safaridriver --enable
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: mvn clean verify -Dthreads=single -Denv=${ENV_UP} -Dbrowser=${Browser_UP} -Dcucumber.filter.tags=${Tag_UP} -Dmaven.test.failure.ignore=true
      - store_artifacts: 
          path: target/surefire-reports
          destination: tr1
      - store_test_results:
          path: target/surefire-reports