
version: 2.1
orbs:
  aws-white-list-circleci-ip: configure/aws-white-list-circleci-ip@1.0.0
  aws-cli: circleci/aws-cli@0.1.13
jobs:
  build:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - checkout
      - aws-white-list-circleci-ip/add
      - aws-white-list-circleci-ip/remove